name=NeuButton
version=1.0.0
author=Ulywae <ulywae@gmail.com>
maintainer=Ulywae <ulywae@gmail.com>
sentence=A lightweight, bitmask-based button library with latching and combination support.
paragraph=NeuButton is an efficient button library that uses bitmasking to handle up to 32 buttons with minimal RAM usage. It supports Latching, LongPress, Repeat, and multi-button Combinations.
category=Signal Input
url=https://github.com/ulywae/NeuButton
architectures=*
