name=NeuButton
version=2.0.1
author=Ulywae <ulywae@gmail.com>
maintainer=Ulywae <ulywae@gmail.com>
sentence=Ultra-low RAM, deterministic multi-button engine using bitmasking.
paragraph=NeuButton v2 introduces a zero-cost template architecture with auto-adaptive masking (8/16/32-bit), drastically reducing RAM usage by up to 60%.
category=Device Control
url=https://github.com/ulywae/NeuButton
architectures=*
